name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn
      - run: make build
      - run: make test

      - uses: JS-DevTools/npm-publish@v2
        if: ${{ github.ref == 'refs/heads/version1' }}
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./package.json
          tag: version1
          access: public
          dry-run: false
          check-version: true
